### ISSUE TITLE
[20240516] 네이버 소셜로그인 이메일 DB 추가, 트러블 슈팅 해결

### ISSUE THREAD

**Issue by janghw0126** [Chaeyeon0/GreenDay_Study#1]
### **😵‍💫 트러블 슈팅 해결 😵‍💫**
> [!Caution]
> **1. 이메일 데이터가 DB에 저장이 되지 않았다.**

![image](https://github.com/Chaeyeon0/GreenDay_Study/assets/127714800/88d2bdb2-fe0b-4ec4-82aa-3f7943bc16fe)

💡 **해결**
- OAuth2 서비스 패키지에 조회된 회원 정보가 없는 경우 정보를 추가하는 부분에서 이메일을 추가해주면 된다.

```java
// 조회된 회원 정보가 없는 경우 새로운 회원으로 등록
        if (findMember == null) {
            member = Member.builder()
                    .loginId(loginId)
                    .name(name)
                    //이메일 추가
                    .email(email)
                    .provider(provider)
                    .providerId(providerId)
                    .role(MemberRole.USER)
                    .build();
            memberRepository.save(member);
        } else{
            member = findMember;
        }
```

- 사용자 정보를 제공하는 OAuth2 공급자에서 사용자의 이메일을 반환하는 메서드도 추가해주면 된다.

```java
String email = oAuth2UserInfo.getEmail();
```
![image](https://github.com/Chaeyeon0/GreenDay_Study/assets/127714800/f6569751-001b-44b7-b1e9-2f6225360fe7)

**해결완!**

<br>

> [!Caution]
> **2. 나중에 게시판을 구현할 때 멤버들을 구분하기 위해서 이메일이 필요할 것 같아 DB에 이메일을 추가했다. 
근데 오류가 생겼다... 프론트 코드에 이메일 데이터가 뜨지 않는다..**

![image](https://github.com/Chaeyeon0/GreenDay_Study/assets/127714800/840f2a03-b028-4822-bea0-5175ea37d330)
-> 일단 이메일 데이터를 네이버 측에 받아서 이미 DB에 잘 저장한 상태이므로 데이터베이스 문제는 아니다.

고로 컨트롤러 문제일 확률이 높음!

💡 **해결**
- 알고보니 해당 변수가 thymelef 컨텍스트에 정의되어 있지 않았다.
- 그러므로 해당 변수를 컨트롤러에 모델로 추가해주면 된다.
```java
// 로그인한 사용자 정보를 가져옴
        Member loginMember = memberService.getLoginMemberByLoginId(loginId);
        // 로그인한 사용자가 있으면 모델에 이름을 추가함
        if (loginMember != null) {
            model.addAttribute("name", loginMember.getName());
            model.addAttribute("email", loginMember.getEmail());
        }
        // home.html 템플릿을 반환 (임시)
        return "home";
    }
```
→ 사용자의 이메일 정보를 모델에 추가하면 된다. 소셜 로그인 성공 시 사용자의 이메일 정보가 이미 존재한다고 가정하고, 해당 이메일 정보를 모델에 추가하면 된다.

![image](https://github.com/Chaeyeon0/GreenDay_Study/assets/127714800/1f211434-cdc5-4008-9c2b-6de9ed1285c4)

**해결완!**

**Comment by Chaeyeon0** [comment]
트러블 슈팅 해결하느라 수고 많았습니다 😆게시판 화이팅 !

**Comment by pu2rile** [comment]
완전 신기하당... 멋있어욧 파이팅파이팅

**Comment by khw010419** [comment]
으악... 어렵다요 수고했어요!!

**Comment by aranlll** [comment]
수고했어용 !!!! 홧팅 !!!!
