### ISSUE TITLE
[20240520] 게시판 수정/삭제 기능 오류 해결 ing...

### ISSUE THREAD

**Issue by janghw0126** [Chaeyeon0/GreenDay_Study#14]
## 게시판 수정/삭제 기능 오류 해결 중..
<img src="https://github.com/Chaeyeon0/GreenDay_Study/assets/127714800/a0cc1001-3cfa-40c5-92ba-d0fd006a629f.png"  width="400" height="300"/>

원래는 이 페이지에서 수정 버튼도 클릭이 안됐었는데 코드 고치고 나서 수정 버튼을 누르니까
![image](https://github.com/Chaeyeon0/GreenDay_Study/assets/127714800/a952ea0b-8749-4d17-bbcf-71b6e7db4f54)
이렇게 수정할 수 있는 페이지까지 떴다 ! 이 부분 오류는 내가 임의로 적은 html을 잘못 적어서 그랬던 것이댜.
글고 이 페이지에서 수정을 하고 수정 버튼을 눌렀더니
<img src="https://github.com/Chaeyeon0/GreenDay_Study/assets/127714800/f4c3aead-32f3-4402-bbfb-04c02c290f50.png"  width="600" height="400"/>

..ㅎ.....

아무래도 컨트롤러 부분이 잘못된 것 같아서 뒤엎고 다시 해야 될 것 같다..

<br>
5/21 - 수정 기능 오류 해결 완....어제 이거 해결한다고 이슈를 제대로 몬썼네요 오늘 이슈에 올리겠씀니다...

**Comment by Chaeyeon0** [comment]
이슈 작성 확인했습니다 ><

**Comment by khw010419** [comment]
오ㅏ 신기해요... 아란이와 혜원이의 합작 게시판 얼른 보고싶어요 ㅎㅎ (정신차려 김효원)
